server:
  port: 18004
spring:
  application:
    name: web-app
  resources:
    static-locations: classpath:/static/
    chain:
      enabled: true
      html-application-cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true