insert into brand (id, name, begin_letter) values (1, 'HTC', 'H');
insert into brand (id, name, begin_letter) values (2, 'LG', 'L');
insert into brand (id, name, begin_letter) values (3, 'NEC', 'N');
insert into brand (id, name, begin_letter) values (4, 'OPPO', 'O');
insert into brand (id, name, begin_letter) values (5, 'TCL', 'T');
insert into brand (id, name, begin_letter) values (6, '爱贝多', 'A');
insert into brand (id, name, begin_letter) values (7, '安桥', 'A');
insert into brand (id, name, begin_letter) values (8, '白金', 'B');
insert into brand (id, name, begin_letter) values (9, '波导A', 'B');
insert into brand (id, name, begin_letter) values (10, '朵唯', 'D');
insert into brand (id, name, begin_letter) values (11, '飞利浦', 'F');
insert into brand (id, name, begin_letter) values (12, '富可视', 'F');
insert into brand (id, name, begin_letter) values (13, '富士通', 'F');
insert into brand (id, name, begin_letter) values (14, '格力', 'G');
insert into brand (id, name, begin_letter) values (15, '海尔', 'H');
insert into brand (id, name, begin_letter) values (16, '海信', 'H');
insert into brand (id, name, begin_letter) values (17, '黑莓', 'H');
insert into brand (id, name, begin_letter) values (18, '华硕', 'H');
insert into brand (id, name, begin_letter) values (19, '华为', 'H');
insert into brand (id, name, begin_letter) values (20, '惠普', 'H');
insert into brand (id, name, begin_letter) values (21, '金立', 'J');
insert into brand (id, name, begin_letter) values (22, '京瓷', 'J');
insert into brand (id, name, begin_letter) values (23, '康佳', 'K');
insert into brand (id, name, begin_letter) values (24, '酷派', 'K');
insert into brand (id, name, begin_letter) values (25, '联想', 'L');
insert into brand (id, name, begin_letter) values (26, '漫步者', 'M');
insert into brand (id, name, begin_letter) values (27, '魅族', 'M');
insert into brand (id, name, begin_letter) values (28, '摩托罗拉', 'M');
insert into brand (id, name, begin_letter) values (29, '诺基亚', 'N');
insert into brand (id, name, begin_letter) values (30, 'Apple', 'A');
insert into brand (id, name, begin_letter) values (31, '青橙', 'Q');
insert into brand (id, name, begin_letter) values (32, '三星', 'S');
insert into brand (id, name, begin_letter) values (33, '神舟', 'S');
insert into brand (id, name, begin_letter) values (34, '索爱', 'S');
insert into brand (id, name, begin_letter) values (35, '索尼', 'S');
insert into brand (id, name, begin_letter) values (36, '天语', 'T');
insert into brand (id, name, begin_letter) values (37, '外星人', 'W');
insert into brand (id, name, begin_letter) values (38, '威图', 'W');
insert into brand (id, name, begin_letter) values (39, '微软', 'W');
insert into brand (id, name, begin_letter) values (40, 'NAMO', 'N');
insert into brand (id, name, begin_letter) values (41, '小辣椒', 'X');
insert into brand (id, name, begin_letter) values (42, '小米', 'X');
insert into brand (id, name, begin_letter) values (43, '优思', 'Y');
insert into brand (id, name, begin_letter) values (44, '长虹', 'C');
insert into brand (id, name, begin_letter) values (45, '中兴', 'Z');
insert into brand (id, name, begin_letter) values (46, 'beats', 'b');
insert into brand (id, name, begin_letter) values (47, '本易', 'B');
insert into brand (id, name, begin_letter) values (48, 'tonino lamborghini', 'T');
insert into brand (id, name, begin_letter) values (49, '布鲁雅尔', 'B');
insert into brand (id, name, begin_letter) values (50, '广信', 'G');
insert into brand (id, name, begin_letter) values (51, '夏普', 'X');
insert into brand (id, name, begin_letter) values (52, '马歇尔', 'M');
insert into brand (id, name, begin_letter) values (53, 'vivo', 'V');
insert into brand (id, name, begin_letter) values (54, '努比亚', 'N');
insert into brand (id, name, begin_letter) values (55, '360', 'S');
insert into brand (id, name, begin_letter) values (56, '其他', 'Q');
insert into brand (id, name, begin_letter) values (57, '金圣达', 'J');
insert into brand (id, name, begin_letter) values (58, '贝尔丰', 'B');
insert into brand (id, name, begin_letter) values (59, '大显（DaXian）', 'D');
insert into brand (id, name, begin_letter) values (60, '朗界（RugGear）', 'L');
insert into brand (id, name, begin_letter) values (61, 'SUGAR', 'S');
insert into brand (id, name, begin_letter) values (62, '美图（meitu）', 'M');
insert into brand (id, name, begin_letter) values (63, 'MANN', 'M');
insert into brand (id, name, begin_letter) values (64, '21KE', 'E');
insert into brand (id, name, begin_letter) values (65, '易百年', 'Y');
insert into brand (id, name, begin_letter) values (66, '威途（vertu）', 'V');
insert into brand (id, name, begin_letter) values (67, '欧奇（ouki）', 'o');
insert into brand (id, name, begin_letter) values (68, 'SPIGEN', 'S');
insert into brand (id, name, begin_letter) values (69, '亿和源（YHYON）', 'Y');
insert into brand (id, name, begin_letter) values (70, 'BIHEE', 'B');
insert into brand (id, name, begin_letter) values (71, '优购（UooGou）', 'Y');
insert into brand (id, name, begin_letter) values (72, '迪美（DIM）', 'D');
insert into brand (id, name, begin_letter) values (73, '尼凯恩（neken）', 'N');
insert into brand (id, name, begin_letter) values (74, 'B&O PLAY', 'B');
insert into brand (id, name, begin_letter) values (75, '誉品（YEPEN）', 'Y');
insert into brand (id, name, begin_letter) values (76, '诺亚信（NOAIN）', 'N');
insert into brand (id, name, begin_letter) values (77, '奥乐迪奥（AoleDior）', 'A');
insert into brand (id, name, begin_letter) values (78, '一加', 'Y');
insert into brand (id, name, begin_letter) values (79, '雷蛇（Razer）', 'L');
insert into brand (id, name, begin_letter) values (80, '詹姆士（GERMY）', 'G');
insert into brand (id, name, begin_letter) values (81, '纽曼（Newman）', 'N');
insert into brand (id, name, begin_letter) values (82, '锤子（smartisan）', 'C');
insert into brand (id, name, begin_letter) values (83, '赛博宇华（SOP）', 'S');
insert into brand (id, name, begin_letter) values (84, '谷歌（Google）', 'G');
insert into brand (id, name, begin_letter) values (85, '爱贝多（Babyfit）', 'A');
insert into brand (id, name, begin_letter) values (86, '万利达（Malata）', 'W');
insert into brand (id, name, begin_letter) values (87, '优它（YOTAPHONE）', 'Y');
insert into brand (id, name, begin_letter) values (88, 'TETC', 'T');
insert into brand (id, name, begin_letter) values (89, '炫华（xuanhua）', 'X');
insert into brand (id, name, begin_letter) values (90, '托尼洛·兰博基尼（Tonino Lamborghini）', 'T');
insert into brand (id, name, begin_letter) values (91, '木糖醇（MuTuCu）', 'M');
insert into brand (id, name, begin_letter) values (92, '爱玛（EMMA）', 'A');
insert into brand (id, name, begin_letter) values (93, '硕尼姆（Sonim）', 'S');
insert into brand (id, name, begin_letter) values (94, 'CAT', 'C');
insert into brand (id, name, begin_letter) values (95, 'ZUK', 'Z');
insert into brand (id, name, begin_letter) values (96, 'sungee', 'S');
insert into brand (id, name, begin_letter) values (97, 'AGM', 'A');
insert into brand (id, name, begin_letter) values (98, 'SOYES', 'S');
insert into brand (id, name, begin_letter) values (99, 'KODAK', 'K');
insert into brand (id, name, begin_letter) values (100, '施耐德（schneider）', 'S');
insert into brand (id, name, begin_letter) values (101, 'MOQI', 'M');
insert into brand (id, name, begin_letter) values (102, 'Essentials', 'E');
insert into brand (id, name, begin_letter) values (103, 'SAMWEI', 'S');
insert into brand (id, name, begin_letter) values (104, '小霸王（SUBOR）', 'X');
insert into brand (id, name, begin_letter) values (105, 'VETAS', 'V');
insert into brand (id, name, begin_letter) values (106, '优学派', 'Y');
insert into brand (id, name, begin_letter) values (107, 'DEVIALET', 'D');
insert into brand (id, name, begin_letter) values (108, 'SHANGPREE', 'S');
insert into brand (id, name, begin_letter) values (109, 'IMOO', 'I');
insert into brand (id, name, begin_letter) values (110, 'FNNI', 'F');
insert into brand (id, name, begin_letter) values (111, '小格雷', 'X');
insert into brand (id, name, begin_letter) values (112, 'COTTEE', 'C');
insert into brand (id, name, begin_letter) values (113, 'YAAO', 'Y');
insert into brand (id, name, begin_letter) values (114, '纽曼', 'N');
insert into brand (id, name, begin_letter) values (115, 'CONQUEST', 'C');
insert into brand (id, name, begin_letter) values (116, '铂爵（BIOJUET）', 'B');
insert into brand (id, name, begin_letter) values (117, '荣耀', 'R');
insert into brand (id, name, begin_letter) values (118, '保千里（PROTRULY）', 'B');
insert into brand (id, name, begin_letter) values (119, 'Blu', 'B');
insert into brand (id, name, begin_letter) values (120, 'unruly', 'U');
insert into brand (id, name, begin_letter) values (121, '守护宝', 'S');
insert into brand (id, name, begin_letter) values (122, '8848', 'B');
insert into brand (id, name, begin_letter) values (123, 'Gold Elite', 'G');
insert into brand (id, name, begin_letter) values (124, 'HONOR', 'H');
insert into brand (id, name, begin_letter) values (125, 'BIXING', 'B');
insert into brand (id, name, begin_letter) values (126, '锐族', 'R');
insert into brand (id, name, begin_letter) values (127, '国美（GOME）', 'G');
insert into brand (id, name, begin_letter) values (128, '中兴健康（ZTE Health）', 'Z');
insert into brand (id, name, begin_letter) values (129, 'YOSTAR', 'Y');
insert into brand (id, name, begin_letter) values (130, '创星', 'C');
insert into brand (id, name, begin_letter) values (131, 'VERTU', 'V');
insert into brand (id, name, begin_letter) values (132, 'LBER', 'L');
insert into brand (id, name, begin_letter) values (133, '滝风（ION MEDIC）', 'L');
insert into brand (id, name, begin_letter) values (134, '梦幻门（MENG HUAN MEN）', 'M');
insert into brand (id, name, begin_letter) values (135, '意龍（E&L）', 'Y');
insert into brand (id, name, begin_letter) values (136, '艾尼卡（Anica）', 'A');
insert into brand (id, name, begin_letter) values (137, 'DMZ DAMUZHI', 'D');
insert into brand (id, name, begin_letter) values (138, 'UNNO', 'U');
insert into brand (id, name, begin_letter) values (139, '红鸟', 'H');
insert into brand (id, name, begin_letter) values (140, '紐萬（Niuwan）', 'N');
insert into brand (id, name, begin_letter) values (141, 'Podor', 'B');
insert into brand (id, name, begin_letter) values (142, '海语（HAIYU）', 'H');
insert into brand (id, name, begin_letter) values (143, 'YISON', 'Y');
insert into brand (id, name, begin_letter) values (144, 'SOAP', 'S');
insert into brand (id, name, begin_letter) values (145, 'renebelle', 'R');
insert into brand (id, name, begin_letter) values (146, 'AKESR', 'A');
insert into brand (id, name, begin_letter) values (147, 'YOTA', 'Y');
insert into brand (id, name, begin_letter) values (148, 'HOOLFINE', 'H');
insert into brand (id, name, begin_letter) values (149, '金柏利', 'J');
insert into brand (id, name, begin_letter) values (150, 'BLACKPOULO', 'B');
insert into brand (id, name, begin_letter) values (151, 'SIMPLEWAY', 'S');
insert into brand (id, name, begin_letter) values (152, 'KaiDC', 'K');
insert into brand (id, name, begin_letter) values (153, '奥缇斯（autrise）', 'A');
insert into brand (id, name, begin_letter) values (154, '橄榄树（Olive tree）', 'G');
insert into brand (id, name, begin_letter) values (155, 'HIGE', 'H');
insert into brand (id, name, begin_letter) values (156, '360手机', 'S');
insert into brand (id, name, begin_letter) values (157, '克里特（kreta）', 'k');
insert into brand (id, name, begin_letter) values (158, 'RONXS', 'R');
insert into brand (id, name, begin_letter) values (159, '飞利浦（PHILIPS）', 'P');
insert into brand (id, name, begin_letter) values (160, '比亚兹（ESK）', 'B');
insert into brand (id, name, begin_letter) values (161, '亿色(ESR)', 'Y');
insert into brand (id, name, begin_letter) values (162, '阿里斯顿', 'A');
insert into brand (id, name, begin_letter) values (163, 'ABC', 'A');
insert into brand (id, name, begin_letter) values (164, '黑马', 'H');
insert into brand (id, name, begin_letter) values (165, '传智', 'C');
insert into brand (id, name, begin_letter) values (166, '迷你', 'M');
insert into brand (id, name, begin_letter) values (167, '新立', 'X');
insert into brand (id, name, begin_letter) values (168, '测试AAAAA', '1');
insert into brand (id, name, begin_letter) values (169, '手机配件', 'S');
insert into brand (id, name, begin_letter) values (170, 'Demo111', 'D');

insert into category(name, parent_id, template_id) values('图书、音像、电子书刊', 0, 1);
insert into category(name, parent_id, template_id) values('电子书刊', 1, 1);
insert into category(name, parent_id, template_id) values('电子书', 2, 1);
insert into category(name, parent_id, template_id) values('网络原创', 2, 1);
insert into category(name, parent_id, template_id) values('数字杂志', 2, 1);
insert into category(name, parent_id, template_id) values('多媒体图书', 2, 1);
insert into category(name, parent_id, template_id) values('音像', 1, 1);
insert into category(name, parent_id, template_id) values('音乐', 7, 1);
insert into category(name, parent_id, template_id) values('影视', 7, 1);
insert into category(name, parent_id, template_id) values('教育音像', 7, 1);
insert into category(name, parent_id, template_id) values('英文原版', 1, 1);
insert into category(name, parent_id, template_id) values('商务投资', 11, 1);
insert into category(name, parent_id, template_id) values('英语学习与考试', 11, 1);
insert into category(name, parent_id, template_id) values('传记', 11, 1);
insert into category(name, parent_id, template_id) values('文艺', 1, 1);
insert into category(name, parent_id, template_id) values('小说', 15, 1);
insert into category(name, parent_id, template_id) values('文学', 15, 1);
insert into category(name, parent_id, template_id) values('青春文学', 15, 1);
insert into category(name, parent_id, template_id) values('艺术', 15, 1);
insert into category(name, parent_id, template_id) values('少儿', 1, 1);
insert into category(name, parent_id, template_id) values('0-2岁', 20, 1);
insert into category(name, parent_id, template_id) values('3-6岁', 20, 1);
insert into category(name, parent_id, template_id) values('7-10岁', 20, 1);
insert into category(name, parent_id, template_id) values('11-14岁', 20, 1);
insert into category(name, parent_id, template_id) values('人文社科', 1, 1);
insert into category(name, parent_id, template_id) values('历史', 25, 1);
insert into category(name, parent_id, template_id) values('哲学', 25, 1);
insert into category(name, parent_id, template_id) values('国学', 25, 1);
insert into category(name, parent_id, template_id) values('政治/军事', 25, 1);
insert into category(name, parent_id, template_id) values('法律', 25, 1);
insert into category(name, parent_id, template_id) values('宗教', 25, 1);
insert into category(name, parent_id, template_id) values('心理学', 25, 1);
insert into category(name, parent_id, template_id) values('文化', 25, 1);
insert into category(name, parent_id, template_id) values('社会科学', 25, 1);
insert into category(name, parent_id, template_id) values('经管励志', 1, 1);
insert into category(name, parent_id, template_id) values('经济', 35, 1);
insert into category(name, parent_id, template_id) values('金融与投资', 35, 1);
insert into category(name, parent_id, template_id) values('管理', 35, 1);
insert into category(name, parent_id, template_id) values('励志与成功', 35, 1);
insert into category(name, parent_id, template_id) values('生活', 1, 1);
insert into category(name, parent_id, template_id) values('健身与保健', 40, 1);
insert into category(name, parent_id, template_id) values('家庭与育儿', 40, 1);
insert into category(name, parent_id, template_id) values('旅游', 40, 1);
insert into category(name, parent_id, template_id) values('动漫/幽默', 40, 1);
insert into category(name, parent_id, template_id) values('科技', 1, 1);
insert into category(name, parent_id, template_id) values('工程', 45, 1);
insert into category(name, parent_id, template_id) values('建筑', 45, 1);
insert into category(name, parent_id, template_id) values('医学', 45, 1);
insert into category(name, parent_id, template_id) values('科学与自然', 45, 1);
insert into category(name, parent_id, template_id) values('计算机与互联网', 45, 1);
insert into category(name, parent_id, template_id) values('体育/运动', 45, 1);
insert into category(name, parent_id, template_id) values('教育', 1, 1);
insert into category(name, parent_id, template_id) values('教材教辅', 52, 1);
insert into category(name, parent_id, template_id) values('教育与考试', 52, 1);
insert into category(name, parent_id, template_id) values('外语学习', 52, 1);
insert into category(name, parent_id, template_id) values('语言文字', 52, 1);
insert into category(name, parent_id, template_id) values('港台图书', 1, 1);
insert into category(name, parent_id, template_id) values('艺术/设计/收藏', 57, 1);
insert into category(name, parent_id, template_id) values('经济管理', 57, 1);
insert into category(name, parent_id, template_id) values('文化/学术', 57, 1);
insert into category(name, parent_id, template_id) values('少儿文学/国学', 57, 1);
insert into category(name, parent_id, template_id) values('其它', 1, 1);
insert into category(name, parent_id, template_id) values('工具书', 62, 1);
insert into category(name, parent_id, template_id) values('影印版', 62, 1);
insert into category(name, parent_id, template_id) values('套装书', 62, 1);
insert into category(name, parent_id, template_id) values('家用电器', 0, 1);
insert into category(name, parent_id, template_id) values('大家电', 66, 1);
insert into category(name, parent_id, template_id) values('平板电视', 67, 1);
insert into category(name, parent_id, template_id) values('空调', 67, 1);
insert into category(name, parent_id, template_id) values('冰箱', 67, 1);
insert into category(name, parent_id, template_id) values('洗衣机', 67, 1);
insert into category(name, parent_id, template_id) values('家庭影院', 67, 1);
insert into category(name, parent_id, template_id) values('DVD播放机', 67, 1);
insert into category(name, parent_id, template_id) values('迷你音响', 67, 1);
insert into category(name, parent_id, template_id) values('烟机/灶具', 67, 1);
insert into category(name, parent_id, template_id) values('热水器', 67, 1);
insert into category(name, parent_id, template_id) values('消毒柜/洗碗机', 67, 1);
insert into category(name, parent_id, template_id) values('酒柜/冰吧/冷柜', 67, 1);
insert into category(name, parent_id, template_id) values('家电配件', 67, 1);
insert into category(name, parent_id, template_id) values('家电下乡', 67, 1);
insert into category(name, parent_id, template_id) values('生活电器', 66, 1);
insert into category(name, parent_id, template_id) values('电风扇', 81, 1);
insert into category(name, parent_id, template_id) values('冷风扇', 81, 1);
insert into category(name, parent_id, template_id) values('净化器', 81, 1);
insert into category(name, parent_id, template_id) values('饮水机', 81, 1);
insert into category(name, parent_id, template_id) values('净水设备', 81, 1);
insert into category(name, parent_id, template_id) values('挂烫机/熨斗', 81, 1);
insert into category(name, parent_id, template_id) values('吸尘器', 81, 1);
insert into category(name, parent_id, template_id) values('电话机', 81, 1);
insert into category(name, parent_id, template_id) values('插座', 81, 1);
insert into category(name, parent_id, template_id) values('收录/音机', 81, 1);
insert into category(name, parent_id, template_id) values('清洁机', 81, 1);
insert into category(name, parent_id, template_id) values('加湿器', 81, 1);
insert into category(name, parent_id, template_id) values('除湿机', 81, 1);
insert into category(name, parent_id, template_id) values('取暖电器', 81, 1);
insert into category(name, parent_id, template_id) values('其它生活电器', 81, 1);
insert into category(name, parent_id, template_id) values('扫地机器人', 81, 1);
insert into category(name, parent_id, template_id) values('干衣机', 81, 1);
insert into category(name, parent_id, template_id) values('生活电器配件', 81, 1);
insert into category(name, parent_id, template_id) values('厨房电器', 66, 1);
insert into category(name, parent_id, template_id) values('料理/榨汁机', 100, 1);
insert into category(name, parent_id, template_id) values('豆浆机', 100, 1);
insert into category(name, parent_id, template_id) values('电饭煲', 100, 1);
insert into category(name, parent_id, template_id) values('电压力锅', 100, 1);
insert into category(name, parent_id, template_id) values('面包机', 100, 1);
insert into category(name, parent_id, template_id) values('咖啡机', 100, 1);
insert into category(name, parent_id, template_id) values('微波炉', 100, 1);
insert into category(name, parent_id, template_id) values('电烤箱', 100, 1);
insert into category(name, parent_id, template_id) values('电磁炉', 100, 1);
insert into category(name, parent_id, template_id) values('电饼铛/烧烤盘', 100, 1);
insert into category(name, parent_id, template_id) values('煮蛋器', 100, 1);
insert into category(name, parent_id, template_id) values('酸奶机', 100, 1);
insert into category(name, parent_id, template_id) values('电炖锅', 100, 1);
insert into category(name, parent_id, template_id) values('电水壶/热水瓶', 100, 1);
insert into category(name, parent_id, template_id) values('多用途锅', 100, 1);
insert into category(name, parent_id, template_id) values('果蔬解毒机', 100, 1);
insert into category(name, parent_id, template_id) values('其它厨房电器', 100, 1);
insert into category(name, parent_id, template_id) values('个护健康', 66, 1);
insert into category(name, parent_id, template_id) values('剃须刀', 118, 1);
insert into category(name, parent_id, template_id) values('剃/脱毛器', 118, 1);
insert into category(name, parent_id, template_id) values('口腔护理', 118, 1);
insert into category(name, parent_id, template_id) values('电吹风', 118, 1);
insert into category(name, parent_id, template_id) values('美容器', 118, 1);
insert into category(name, parent_id, template_id) values('美发器', 118, 1);
insert into category(name, parent_id, template_id) values('按摩椅', 118, 1);
insert into category(name, parent_id, template_id) values('按摩器', 118, 1);
insert into category(name, parent_id, template_id) values('足浴盆', 118, 1);
insert into category(name, parent_id, template_id) values('血压计', 118, 1);
insert into category(name, parent_id, template_id) values('健康秤/厨房秤', 118, 1);
insert into category(name, parent_id, template_id) values('血糖仪', 118, 1);
insert into category(name, parent_id, template_id) values('体温计', 118, 1);
insert into category(name, parent_id, template_id) values('计步器/脂肪检测仪', 118, 1);
insert into category(name, parent_id, template_id) values('其它健康电器', 118, 1);
insert into category(name, parent_id, template_id) values('五金家装', 66, 1);
insert into category(name, parent_id, template_id) values('电动工具', 134, 1);
insert into category(name, parent_id, template_id) values('手动工具', 134, 1);
insert into category(name, parent_id, template_id) values('仪器仪表', 134, 1);
insert into category(name, parent_id, template_id) values('浴霸/排气扇', 134, 1);
insert into category(name, parent_id, template_id) values('灯具', 134, 1);
insert into category(name, parent_id, template_id) values('LED灯', 134, 1);
insert into category(name, parent_id, template_id) values('洁身器', 134, 1);
insert into category(name, parent_id, template_id) values('水槽', 134, 1);
insert into category(name, parent_id, template_id) values('龙头', 134, 1);
insert into category(name, parent_id, template_id) values('淋浴花洒', 134, 1);
insert into category(name, parent_id, template_id) values('厨卫五金', 134, 1);
insert into category(name, parent_id, template_id) values('家具五金', 134, 1);
insert into category(name, parent_id, template_id) values('门铃', 134, 1);
insert into category(name, parent_id, template_id) values('电气开关', 134, 1);
insert into category(name, parent_id, template_id) values('电工电料', 134, 1);
insert into category(name, parent_id, template_id) values('监控安防', 134, 1);
insert into category(name, parent_id, template_id) values('电线线缆', 134, 1);
insert into category(name, parent_id, template_id) values('电脑、办公', 0, 1);
insert into category(name, parent_id, template_id) values('电脑整机', 152, 1);
insert into category(name, parent_id, template_id) values('笔记本', 153, 1);
insert into category(name, parent_id, template_id) values('超极本', 153, 1);
insert into category(name, parent_id, template_id) values('游戏本', 153, 1);
insert into category(name, parent_id, template_id) values('平板电脑', 153, 1);
insert into category(name, parent_id, template_id) values('平板电脑配件', 153, 1);
insert into category(name, parent_id, template_id) values('台式机', 153, 1);
insert into category(name, parent_id, template_id) values('服务器/工作站', 153, 1);
insert into category(name, parent_id, template_id) values('笔记本配件', 153, 1);
insert into category(name, parent_id, template_id) values('电脑配件', 152, 1);
insert into category(name, parent_id, template_id) values('CPU', 162, 1);
insert into category(name, parent_id, template_id) values('主板', 162, 1);
insert into category(name, parent_id, template_id) values('显卡', 162, 1);
insert into category(name, parent_id, template_id) values('硬盘', 162, 1);
insert into category(name, parent_id, template_id) values('SSD固态硬盘', 162, 1);
insert into category(name, parent_id, template_id) values('内存', 162, 1);
insert into category(name, parent_id, template_id) values('机箱', 162, 1);
insert into category(name, parent_id, template_id) values('电源', 162, 1);
insert into category(name, parent_id, template_id) values('显示器', 162, 1);
insert into category(name, parent_id, template_id) values('刻录机/光驱', 162, 1);
insert into category(name, parent_id, template_id) values('散热器', 162, 1);
insert into category(name, parent_id, template_id) values('声卡/扩展卡', 162, 1);
insert into category(name, parent_id, template_id) values('装机配件', 162, 1);
insert into category(name, parent_id, template_id) values('组装电脑', 162, 1);
insert into category(name, parent_id, template_id) values('外设产品', 152, 1);
insert into category(name, parent_id, template_id) values('移动硬盘', 177, 1);
insert into category(name, parent_id, template_id) values('U盘', 177, 1);
insert into category(name, parent_id, template_id) values('鼠标', 177, 1);
insert into category(name, parent_id, template_id) values('键盘', 177, 1);
insert into category(name, parent_id, template_id) values('鼠标垫', 177, 1);
insert into category(name, parent_id, template_id) values('摄像头', 177, 1);
insert into category(name, parent_id, template_id) values('手写板', 177, 1);
insert into category(name, parent_id, template_id) values('外置盒', 177, 1);
insert into category(name, parent_id, template_id) values('线缆', 177, 1);
insert into category(name, parent_id, template_id) values('UPS电源', 177, 1);
insert into category(name, parent_id, template_id) values('电脑工具', 177, 1);
insert into category(name, parent_id, template_id) values('游戏设备', 177, 1);
insert into category(name, parent_id, template_id) values('电玩', 177, 1);
insert into category(name, parent_id, template_id) values('电脑清洁', 177, 1);
insert into category(name, parent_id, template_id) values('网络产品', 152, 1);
insert into category(name, parent_id, template_id) values('路由器', 192, 1);
insert into category(name, parent_id, template_id) values('网卡', 192, 1);
insert into category(name, parent_id, template_id) values('交换机', 192, 1);
insert into category(name, parent_id, template_id) values('网络存储', 192, 1);
insert into category(name, parent_id, template_id) values('4G/3G上网', 192, 1);
insert into category(name, parent_id, template_id) values('网络盒子', 192, 1);
insert into category(name, parent_id, template_id) values('网络配件', 192, 1);
insert into category(name, parent_id, template_id) values('办公设备', 152, 1);
insert into category(name, parent_id, template_id) values('投影机', 200, 1);
insert into category(name, parent_id, template_id) values('投影配件', 200, 1);
insert into category(name, parent_id, template_id) values('多功能一体机', 200, 1);
insert into category(name, parent_id, template_id) values('打印机', 200, 1);
insert into category(name, parent_id, template_id) values('传真设备', 200, 1);
insert into category(name, parent_id, template_id) values('验钞/点钞机', 200, 1);
insert into category(name, parent_id, template_id) values('扫描设备', 200, 1);
insert into category(name, parent_id, template_id) values('复合机', 200, 1);
insert into category(name, parent_id, template_id) values('碎纸机', 200, 1);
insert into category(name, parent_id, template_id) values('考勤机', 200, 1);
insert into category(name, parent_id, template_id) values('墨粉', 200, 1);
insert into category(name, parent_id, template_id) values('收款/POS机', 200, 1);
insert into category(name, parent_id, template_id) values('会议音频视频', 200, 1);
insert into category(name, parent_id, template_id) values('保险柜', 200, 1);
insert into category(name, parent_id, template_id) values('装订/封装机', 200, 1);
insert into category(name, parent_id, template_id) values('安防监控', 200, 1);
insert into category(name, parent_id, template_id) values('办公家具', 200, 1);
insert into category(name, parent_id, template_id) values('白板', 200, 1);
insert into category(name, parent_id, template_id) values('文具/耗材', 152, 1);
insert into category(name, parent_id, template_id) values('硒鼓/墨粉', 219, 1);
insert into category(name, parent_id, template_id) values('墨盒', 219, 1);
insert into category(name, parent_id, template_id) values('色带', 219, 1);
insert into category(name, parent_id, template_id) values('纸类', 219, 1);
insert into category(name, parent_id, template_id) values('办公文具', 219, 1);
insert into category(name, parent_id, template_id) values('学生文具', 219, 1);
insert into category(name, parent_id, template_id) values('文件管理', 219, 1);
insert into category(name, parent_id, template_id) values('财会用品', 219, 1);
insert into category(name, parent_id, template_id) values('本册/便签', 219, 1);
insert into category(name, parent_id, template_id) values('计算器', 219, 1);
insert into category(name, parent_id, template_id) values('激光笔', 219, 1);
insert into category(name, parent_id, template_id) values('笔类', 219, 1);
insert into category(name, parent_id, template_id) values('画具画材', 219, 1);
insert into category(name, parent_id, template_id) values('刻录碟片/附件', 219, 1);
insert into category(name, parent_id, template_id) values('服务产品', 152, 1);
insert into category(name, parent_id, template_id) values('上门服务', 234, 1);
insert into category(name, parent_id, template_id) values('远程服务', 234, 1);
insert into category(name, parent_id, template_id) values('电脑软件', 234, 1);
insert into category(name, parent_id, template_id) values('京东服务', 234, 1);
insert into category(name, parent_id, template_id) values('个护化妆', 0, 1);
insert into category(name, parent_id, template_id) values('面部护肤', 239, 1);
insert into category(name, parent_id, template_id) values('清洁', 240, 1);
insert into category(name, parent_id, template_id) values('护肤', 240, 1);
insert into category(name, parent_id, template_id) values('面膜', 240, 1);
insert into category(name, parent_id, template_id) values('剃须', 240, 1);
insert into category(name, parent_id, template_id) values('套装', 240, 1);
insert into category(name, parent_id, template_id) values('身体护肤', 239, 1);
insert into category(name, parent_id, template_id) values('沐浴', 246, 1);
insert into category(name, parent_id, template_id) values('润肤', 246, 1);
insert into category(name, parent_id, template_id) values('颈部', 246, 1);
insert into category(name, parent_id, template_id) values('手足', 246, 1);
insert into category(name, parent_id, template_id) values('纤体塑形', 246, 1);
insert into category(name, parent_id, template_id) values('美胸', 246, 1);
insert into category(name, parent_id, template_id) values('牙膏/牙粉', 0, 1);
insert into category(name, parent_id, template_id) values('牙刷/牙线', 0, 1);
insert into category(name, parent_id, template_id) values('漱口水', 0, 1);
insert into category(name, parent_id, template_id) values('女性护理', 239, 1);
insert into category(name, parent_id, template_id) values('卫生巾', 256, 1);
insert into category(name, parent_id, template_id) values('卫生护垫', 256, 1);
insert into category(name, parent_id, template_id) values('私密护理', 256, 1);
insert into category(name, parent_id, template_id) values('脱毛膏', 256, 1);
insert into category(name, parent_id, template_id) values('洗发护发', 239, 1);
insert into category(name, parent_id, template_id) values('洗发', 261, 1);
insert into category(name, parent_id, template_id) values('护发', 261, 1);
insert into category(name, parent_id, template_id) values('染发', 261, 1);
insert into category(name, parent_id, template_id) values('造型', 261, 1);
insert into category(name, parent_id, template_id) values('假发', 261, 1);
insert into category(name, parent_id, template_id) values('香水彩妆', 239, 1);
insert into category(name, parent_id, template_id) values('香水', 267, 1);
insert into category(name, parent_id, template_id) values('底妆', 267, 1);
insert into category(name, parent_id, template_id) values('腮红', 267, 1);
insert into category(name, parent_id, template_id) values('眼部', 267, 1);
insert into category(name, parent_id, template_id) values('唇部', 267, 1);
insert into category(name, parent_id, template_id) values('美甲', 267, 1);
insert into category(name, parent_id, template_id) values('美容工具', 267, 1);
insert into category(name, parent_id, template_id) values('钟表', 0, 1);
insert into category(name, parent_id, template_id) values('男表', 0, 1);
insert into category(name, parent_id, template_id) values('女表', 0, 1);
insert into category(name, parent_id, template_id) values('儿童手表', 0, 1);
insert into category(name, parent_id, template_id) values('座钟挂钟', 0, 1);
insert into category(name, parent_id, template_id) values('母婴', 0, 1);
insert into category(name, parent_id, template_id) values('奶粉', 280, 1);
insert into category(name, parent_id, template_id) values('婴幼奶粉', 281, 1);
insert into category(name, parent_id, template_id) values('成人奶粉', 281, 1);
insert into category(name, parent_id, template_id) values('营养辅食', 280, 1);
insert into category(name, parent_id, template_id) values('益生菌/初乳', 284, 1);
insert into category(name, parent_id, template_id) values('米粉/菜粉', 284, 1);
insert into category(name, parent_id, template_id) values('果泥/果汁', 284, 1);
insert into category(name, parent_id, template_id) values('DHA', 284, 1);
insert into category(name, parent_id, template_id) values('宝宝零食', 284, 1);
insert into category(name, parent_id, template_id) values('钙铁锌/维生素', 284, 1);
insert into category(name, parent_id, template_id) values('清火/开胃', 284, 1);
insert into category(name, parent_id, template_id) values('面条/粥', 284, 1);
insert into category(name, parent_id, template_id) values('尿裤湿巾', 280, 1);
insert into category(name, parent_id, template_id) values('婴儿尿裤', 293, 1);
insert into category(name, parent_id, template_id) values('拉拉裤', 293, 1);
insert into category(name, parent_id, template_id) values('湿巾', 293, 1);
insert into category(name, parent_id, template_id) values('成人尿裤', 293, 1);
insert into category(name, parent_id, template_id) values('喂养用品', 280, 1);
insert into category(name, parent_id, template_id) values('奶瓶奶嘴', 298, 1);
insert into category(name, parent_id, template_id) values('吸奶器', 298, 1);
insert into category(name, parent_id, template_id) values('暖奶消毒', 298, 1);
insert into category(name, parent_id, template_id) values('碗盘叉勺', 298, 1);
insert into category(name, parent_id, template_id) values('水壶/水杯', 298, 1);
insert into category(name, parent_id, template_id) values('牙胶安抚', 298, 1);
insert into category(name, parent_id, template_id) values('辅食料理机', 298, 1);
insert into category(name, parent_id, template_id) values('洗护用品', 280, 1);
insert into category(name, parent_id, template_id) values('宝宝护肤', 306, 1);
insert into category(name, parent_id, template_id) values('宝宝洗浴', 306, 1);
insert into category(name, parent_id, template_id) values('奶瓶清洗', 306, 1);
insert into category(name, parent_id, template_id) values('驱蚊防蚊', 306, 1);
insert into category(name, parent_id, template_id) values('理发器', 306, 1);
insert into category(name, parent_id, template_id) values('洗衣液/皂', 306, 1);
insert into category(name, parent_id, template_id) values('日常护理', 306, 1);
insert into category(name, parent_id, template_id) values('座便器', 306, 1);
insert into category(name, parent_id, template_id) values('童车童床', 280, 1);
insert into category(name, parent_id, template_id) values('婴儿推车', 315, 1);
insert into category(name, parent_id, template_id) values('餐椅摇椅', 315, 1);
insert into category(name, parent_id, template_id) values('婴儿床', 315, 1);
insert into category(name, parent_id, template_id) values('学步车', 315, 1);
insert into category(name, parent_id, template_id) values('三轮车', 315, 1);
insert into category(name, parent_id, template_id) values('自行车', 315, 1);
insert into category(name, parent_id, template_id) values('电动车', 315, 1);
insert into category(name, parent_id, template_id) values('扭扭车', 315, 1);
insert into category(name, parent_id, template_id) values('滑板车', 315, 1);
insert into category(name, parent_id, template_id) values('寝居服饰', 280, 1);
insert into category(name, parent_id, template_id) values('婴儿外出服', 325, 1);
insert into category(name, parent_id, template_id) values('婴儿内衣', 325, 1);
insert into category(name, parent_id, template_id) values('婴儿礼盒', 325, 1);
insert into category(name, parent_id, template_id) values('婴儿鞋帽袜', 325, 1);
insert into category(name, parent_id, template_id) values('安全防护', 325, 1);
insert into category(name, parent_id, template_id) values('家居床品', 325, 1);
insert into category(name, parent_id, template_id) values('妈妈专区', 280, 1);
insert into category(name, parent_id, template_id) values('妈咪包/背婴带', 332, 1);
insert into category(name, parent_id, template_id) values('产后塑身', 332, 1);
insert into category(name, parent_id, template_id) values('文胸/内裤', 332, 1);
insert into category(name, parent_id, template_id) values('防辐射服', 332, 1);
insert into category(name, parent_id, template_id) values('孕妇装', 332, 1);
insert into category(name, parent_id, template_id) values('孕期营养', 332, 1);
insert into category(name, parent_id, template_id) values('孕妈美容', 332, 1);
insert into category(name, parent_id, template_id) values('待产/新生', 332, 1);
insert into category(name, parent_id, template_id) values('月子装', 332, 1);
insert into category(name, parent_id, template_id) values('童装童鞋', 280, 1);
insert into category(name, parent_id, template_id) values('上衣', 342, 1);
insert into category(name, parent_id, template_id) values('裤子', 342, 1);
insert into category(name, parent_id, template_id) values('裙子', 342, 1);
insert into category(name, parent_id, template_id) values('内衣/家居服', 342, 1);
insert into category(name, parent_id, template_id) values('羽绒服/棉服', 342, 1);
insert into category(name, parent_id, template_id) values('亲子装', 342, 1);
insert into category(name, parent_id, template_id) values('儿童配饰', 342, 1);
insert into category(name, parent_id, template_id) values('礼服/演出服', 342, 1);
insert into category(name, parent_id, template_id) values('运动鞋', 342, 1);
insert into category(name, parent_id, template_id) values('皮鞋/帆布鞋', 342, 1);
insert into category(name, parent_id, template_id) values('靴子', 342, 1);
insert into category(name, parent_id, template_id) values('凉鞋', 342, 1);
insert into category(name, parent_id, template_id) values('功能鞋', 342, 1);
insert into category(name, parent_id, template_id) values('户外/运动服', 342, 1);
insert into category(name, parent_id, template_id) values('安全座椅', 280, 1);
insert into category(name, parent_id, template_id) values('提篮式', 357, 1);
insert into category(name, parent_id, template_id) values('增高垫', 357, 1);
insert into category(name, parent_id, template_id) values('食品饮料、保健食品', 0, 1);
insert into category(name, parent_id, template_id) values('进口食品', 360, 1);
insert into category(name, parent_id, template_id) values('饼干蛋糕', 361, 1);
insert into category(name, parent_id, template_id) values('糖果/巧克力', 361, 1);
insert into category(name, parent_id, template_id) values('休闲零食', 361, 1);
insert into category(name, parent_id, template_id) values('冲调饮品', 361, 1);
insert into category(name, parent_id, template_id) values('粮油调味', 361, 1);
insert into category(name, parent_id, template_id) values('牛奶', 361, 1);
insert into category(name, parent_id, template_id) values('地方特产', 360, 1);
insert into category(name, parent_id, template_id) values('其他特产', 368, 1);
insert into category(name, parent_id, template_id) values('新疆', 368, 1);
insert into category(name, parent_id, template_id) values('北京', 368, 1);
insert into category(name, parent_id, template_id) values('山西', 368, 1);
insert into category(name, parent_id, template_id) values('内蒙古', 368, 1);
insert into category(name, parent_id, template_id) values('福建', 368, 1);
insert into category(name, parent_id, template_id) values('湖南', 368, 1);
insert into category(name, parent_id, template_id) values('四川', 368, 1);
insert into category(name, parent_id, template_id) values('云南', 368, 1);
insert into category(name, parent_id, template_id) values('东北', 368, 1);
insert into category(name, parent_id, template_id) values('休闲食品', 360, 1);
insert into category(name, parent_id, template_id) values('坚果炒货', 379, 1);
insert into category(name, parent_id, template_id) values('肉干肉脯', 379, 1);
insert into category(name, parent_id, template_id) values('蜜饯果干', 379, 1);
insert into category(name, parent_id, template_id) values('无糖食品', 379, 1);
insert into category(name, parent_id, template_id) values('米面杂粮', 0, 1);
insert into category(name, parent_id, template_id) values('食用油', 0, 1);
insert into category(name, parent_id, template_id) values('调味品', 0, 1);
insert into category(name, parent_id, template_id) values('南北干货', 0, 1);
insert into category(name, parent_id, template_id) values('方便食品', 0, 1);
insert into category(name, parent_id, template_id) values('有机食品', 0, 1);
insert into category(name, parent_id, template_id) values('饮料冲调', 360, 1);
insert into category(name, parent_id, template_id) values('饮用水', 390, 1);
insert into category(name, parent_id, template_id) values('饮料', 390, 1);
insert into category(name, parent_id, template_id) values('牛奶乳品', 390, 1);
insert into category(name, parent_id, template_id) values('咖啡/奶茶', 390, 1);
insert into category(name, parent_id, template_id) values('冲饮谷物', 390, 1);
insert into category(name, parent_id, template_id) values('蜂蜜/柚子茶', 390, 1);
insert into category(name, parent_id, template_id) values('食品礼券', 360, 1);
insert into category(name, parent_id, template_id) values('月饼', 397, 1);
insert into category(name, parent_id, template_id) values('大闸蟹', 397, 1);
insert into category(name, parent_id, template_id) values('粽子', 397, 1);
insert into category(name, parent_id, template_id) values('卡券', 397, 1);
insert into category(name, parent_id, template_id) values('茗茶', 360, 1);
insert into category(name, parent_id, template_id) values('铁观音', 402, 1);
insert into category(name, parent_id, template_id) values('普洱', 402, 1);
insert into category(name, parent_id, template_id) values('龙井', 402, 1);
insert into category(name, parent_id, template_id) values('绿茶', 402, 1);
insert into category(name, parent_id, template_id) values('红茶', 402, 1);
insert into category(name, parent_id, template_id) values('乌龙茶', 402, 1);
insert into category(name, parent_id, template_id) values('花草茶', 402, 1);
insert into category(name, parent_id, template_id) values('花果茶', 402, 1);
insert into category(name, parent_id, template_id) values('养生茶', 402, 1);
insert into category(name, parent_id, template_id) values('黑茶', 402, 1);
insert into category(name, parent_id, template_id) values('白茶', 402, 1);
insert into category(name, parent_id, template_id) values('其它茶', 402, 1);
insert into category(name, parent_id, template_id) values('汽车用品', 0, 1);
insert into category(name, parent_id, template_id) values('维修保养', 415, 1);
insert into category(name, parent_id, template_id) values('润滑油', 416, 1);
insert into category(name, parent_id, template_id) values('添加剂', 416, 1);
insert into category(name, parent_id, template_id) values('防冻液', 416, 1);
insert into category(name, parent_id, template_id) values('滤清器', 416, 1);
insert into category(name, parent_id, template_id) values('火花塞', 416, 1);
insert into category(name, parent_id, template_id) values('雨刷', 416, 1);
insert into category(name, parent_id, template_id) values('车灯', 416, 1);
insert into category(name, parent_id, template_id) values('后视镜', 416, 1);
insert into category(name, parent_id, template_id) values('轮胎', 416, 1);
insert into category(name, parent_id, template_id) values('轮毂', 416, 1);
insert into category(name, parent_id, template_id) values('刹车片/盘', 416, 1);
insert into category(name, parent_id, template_id) values('喇叭/皮带', 416, 1);
insert into category(name, parent_id, template_id) values('蓄电池', 416, 1);
insert into category(name, parent_id, template_id) values('底盘装甲/护板', 416, 1);
insert into category(name, parent_id, template_id) values('贴膜', 416, 1);
insert into category(name, parent_id, template_id) values('汽修工具', 416, 1);
insert into category(name, parent_id, template_id) values('车载电器', 415, 1);
insert into category(name, parent_id, template_id) values('导航仪', 433, 1);
insert into category(name, parent_id, template_id) values('安全预警仪', 433, 1);
insert into category(name, parent_id, template_id) values('行车记录仪', 433, 1);
insert into category(name, parent_id, template_id) values('倒车雷达', 433, 1);
insert into category(name, parent_id, template_id) values('蓝牙设备', 433, 1);
insert into category(name, parent_id, template_id) values('时尚影音', 433, 1);
insert into category(name, parent_id, template_id) values('美容清洗', 415, 1);
insert into category(name, parent_id, template_id) values('车蜡', 440, 1);
insert into category(name, parent_id, template_id) values('补漆笔', 440, 1);
insert into category(name, parent_id, template_id) values('玻璃水', 440, 1);
insert into category(name, parent_id, template_id) values('清洁剂', 440, 1);
insert into category(name, parent_id, template_id) values('洗车工具', 440, 1);
insert into category(name, parent_id, template_id) values('洗车配件', 440, 1);
insert into category(name, parent_id, template_id) values('汽车装饰', 415, 1);
insert into category(name, parent_id, template_id) values('脚垫', 447, 1);
insert into category(name, parent_id, template_id) values('座垫', 447, 1);
insert into category(name, parent_id, template_id) values('座套', 447, 1);
insert into category(name, parent_id, template_id) values('后备箱垫', 447, 1);
insert into category(name, parent_id, template_id) values('头枕腰靠', 447, 1);
insert into category(name, parent_id, template_id) values('空气净化', 447, 1);
insert into category(name, parent_id, template_id) values('车内饰品', 447, 1);
insert into category(name, parent_id, template_id) values('功能小件', 447, 1);
insert into category(name, parent_id, template_id) values('车身装饰件', 447, 1);
insert into category(name, parent_id, template_id) values('车衣', 447, 1);
insert into category(name, parent_id, template_id) values('安全自驾', 415, 1);
insert into category(name, parent_id, template_id) values('胎压充气', 458, 1);
insert into category(name, parent_id, template_id) values('防盗设备', 458, 1);
insert into category(name, parent_id, template_id) values('应急救援', 458, 1);
insert into category(name, parent_id, template_id) values('保温箱', 458, 1);
insert into category(name, parent_id, template_id) values('储物箱', 458, 1);
insert into category(name, parent_id, template_id) values('自驾野营', 458, 1);
insert into category(name, parent_id, template_id) values('摩托车装备', 458, 1);
insert into category(name, parent_id, template_id) values('玩具乐器', 0, 1);
insert into category(name, parent_id, template_id) values('适用年龄', 466, 1);
insert into category(name, parent_id, template_id) values('0-6个月', 467, 1);
insert into category(name, parent_id, template_id) values('6-12个月', 467, 1);
insert into category(name, parent_id, template_id) values('1-3岁', 467, 1);
insert into category(name, parent_id, template_id) values('6-14岁', 467, 1);
insert into category(name, parent_id, template_id) values('14岁以上', 467, 1);
insert into category(name, parent_id, template_id) values('遥控/电动', 466, 1);
insert into category(name, parent_id, template_id) values('遥控车', 473, 1);
insert into category(name, parent_id, template_id) values('遥控飞机', 473, 1);
insert into category(name, parent_id, template_id) values('遥控船', 473, 1);
insert into category(name, parent_id, template_id) values('机器人/电动', 473, 1);
insert into category(name, parent_id, template_id) values('轨道/助力', 473, 1);
insert into category(name, parent_id, template_id) values('毛绒布艺', 466, 1);
insert into category(name, parent_id, template_id) values('毛绒/布艺', 479, 1);
insert into category(name, parent_id, template_id) values('靠垫/抱枕', 479, 1);
insert into category(name, parent_id, template_id) values('娃娃玩具', 466, 1);
insert into category(name, parent_id, template_id) values('芭比娃娃', 482, 1);
insert into category(name, parent_id, template_id) values('卡通娃娃', 482, 1);
insert into category(name, parent_id, template_id) values('智能娃娃', 482, 1);
insert into category(name, parent_id, template_id) values('模型玩具', 466, 1);
insert into category(name, parent_id, template_id) values('仿真模型', 486, 1);
insert into category(name, parent_id, template_id) values('拼插模型', 486, 1);
insert into category(name, parent_id, template_id) values('收藏爱好', 486, 1);
insert into category(name, parent_id, template_id) values('健身玩具', 466, 1);
insert into category(name, parent_id, template_id) values('炫舞毯', 490, 1);
insert into category(name, parent_id, template_id) values('爬行垫/毯', 490, 1);
insert into category(name, parent_id, template_id) values('户外玩具', 490, 1);
insert into category(name, parent_id, template_id) values('戏水玩具', 490, 1);
insert into category(name, parent_id, template_id) values('动漫玩具', 466, 1);
insert into category(name, parent_id, template_id) values('电影周边', 495, 1);
insert into category(name, parent_id, template_id) values('卡通周边', 495, 1);
insert into category(name, parent_id, template_id) values('网游周边', 495, 1);
insert into category(name, parent_id, template_id) values('益智玩具', 466, 1);
insert into category(name, parent_id, template_id) values('摇铃/床铃', 499, 1);
insert into category(name, parent_id, template_id) values('健身架', 499, 1);
insert into category(name, parent_id, template_id) values('早教启智', 499, 1);
insert into category(name, parent_id, template_id) values('拖拉玩具', 499, 1);
insert into category(name, parent_id, template_id) values('积木拼插', 466, 1);
insert into category(name, parent_id, template_id) values('积木', 504, 1);
insert into category(name, parent_id, template_id) values('拼图', 504, 1);
insert into category(name, parent_id, template_id) values('磁力棒', 504, 1);
insert into category(name, parent_id, template_id) values('立体拼插', 504, 1);
insert into category(name, parent_id, template_id) values('DIY玩具', 466, 1);
insert into category(name, parent_id, template_id) values('手工彩泥', 509, 1);
insert into category(name, parent_id, template_id) values('绘画工具', 509, 1);
insert into category(name, parent_id, template_id) values('情景玩具', 509, 1);
insert into category(name, parent_id, template_id) values('创意减压', 466, 1);
insert into category(name, parent_id, template_id) values('减压玩具', 513, 1);
insert into category(name, parent_id, template_id) values('创意玩具', 513, 1);
insert into category(name, parent_id, template_id) values('乐器相关', 466, 1);
insert into category(name, parent_id, template_id) values('钢琴', 516, 1);
insert into category(name, parent_id, template_id) values('电子琴', 516, 1);
insert into category(name, parent_id, template_id) values('手风琴', 516, 1);
insert into category(name, parent_id, template_id) values('吉他/贝斯', 516, 1);
insert into category(name, parent_id, template_id) values('民族管弦乐器', 516, 1);
insert into category(name, parent_id, template_id) values('西洋管弦乐', 516, 1);
insert into category(name, parent_id, template_id) values('口琴/口风琴/竖笛', 516, 1);
insert into category(name, parent_id, template_id) values('西洋打击乐器', 516, 1);
insert into category(name, parent_id, template_id) values('各式乐器配件', 516, 1);
insert into category(name, parent_id, template_id) values('电脑音乐', 516, 1);
insert into category(name, parent_id, template_id) values('工艺礼品乐器', 516, 1);
insert into category(name, parent_id, template_id) values('手机', 0, 1);
insert into category(name, parent_id, template_id) values('手机通讯', 528, 1);
insert into category(name, parent_id, template_id) values('对讲机', 529, 1);
insert into category(name, parent_id, template_id) values('运营商', 528, 1);
insert into category(name, parent_id, template_id) values('购机送费', 531, 1);
insert into category(name, parent_id, template_id) values('“0”元购机', 531, 1);
insert into category(name, parent_id, template_id) values('选号中心', 531, 1);
insert into category(name, parent_id, template_id) values('选号入网', 531, 1);
insert into category(name, parent_id, template_id) values('手机配件', 528, 1);
insert into category(name, parent_id, template_id) values('手机电池', 536, 1);
insert into category(name, parent_id, template_id) values('蓝牙耳机', 536, 1);
insert into category(name, parent_id, template_id) values('充电器/数据线', 536, 1);
insert into category(name, parent_id, template_id) values('手机耳机', 536, 1);
insert into category(name, parent_id, template_id) values('手机贴膜', 536, 1);
insert into category(name, parent_id, template_id) values('手机存储卡', 536, 1);
insert into category(name, parent_id, template_id) values('手机保护套', 536, 1);
insert into category(name, parent_id, template_id) values('车载配件', 536, 1);
insert into category(name, parent_id, template_id) values('iPhone 配件', 536, 1);
insert into category(name, parent_id, template_id) values('创意配件', 536, 1);
insert into category(name, parent_id, template_id) values('便携/无线音响', 536, 1);
insert into category(name, parent_id, template_id) values('手机饰品', 536, 1);
insert into category(name, parent_id, template_id) values('数码', 0, 1);
insert into category(name, parent_id, template_id) values('摄影摄像', 549, 1);
insert into category(name, parent_id, template_id) values('数码相机', 550, 1);
insert into category(name, parent_id, template_id) values('单电/微单相机', 550, 1);
insert into category(name, parent_id, template_id) values('单反相机', 550, 1);
insert into category(name, parent_id, template_id) values('摄像机', 550, 1);
insert into category(name, parent_id, template_id) values('拍立得', 550, 1);
insert into category(name, parent_id, template_id) values('运动相机', 550, 1);
insert into category(name, parent_id, template_id) values('镜头', 550, 1);
insert into category(name, parent_id, template_id) values('户外器材', 550, 1);
insert into category(name, parent_id, template_id) values('影棚器材', 550, 1);
insert into category(name, parent_id, template_id) values('数码配件', 549, 1);
insert into category(name, parent_id, template_id) values('存储卡', 560, 1);
insert into category(name, parent_id, template_id) values('读卡器', 560, 1);
insert into category(name, parent_id, template_id) values('滤镜', 560, 1);
insert into category(name, parent_id, template_id) values('闪光灯/手柄', 560, 1);
insert into category(name, parent_id, template_id) values('相机包', 560, 1);
insert into category(name, parent_id, template_id) values('三脚架/云台', 560, 1);
insert into category(name, parent_id, template_id) values('相机清洁', 560, 1);
insert into category(name, parent_id, template_id) values('相机贴膜', 560, 1);
insert into category(name, parent_id, template_id) values('机身附件', 560, 1);
insert into category(name, parent_id, template_id) values('镜头附件', 560, 1);
insert into category(name, parent_id, template_id) values('电池/充电器', 560, 1);
insert into category(name, parent_id, template_id) values('移动电源', 560, 1);
insert into category(name, parent_id, template_id) values('智能设备', 549, 1);
insert into category(name, parent_id, template_id) values('智能手环', 573, 1);
insert into category(name, parent_id, template_id) values('智能手表', 573, 1);
insert into category(name, parent_id, template_id) values('智能眼镜', 573, 1);
insert into category(name, parent_id, template_id) values('运动跟踪器', 573, 1);
insert into category(name, parent_id, template_id) values('健康监测', 573, 1);
insert into category(name, parent_id, template_id) values('智能配饰', 573, 1);
insert into category(name, parent_id, template_id) values('智能家居', 573, 1);
insert into category(name, parent_id, template_id) values('体感车', 573, 1);
insert into category(name, parent_id, template_id) values('其他配件', 573, 1);
insert into category(name, parent_id, template_id) values('MP3/MP4', 0, 1);
insert into category(name, parent_id, template_id) values('耳机/耳麦', 0, 1);
insert into category(name, parent_id, template_id) values('音箱', 0, 1);
insert into category(name, parent_id, template_id) values('高清播放器', 0, 1);
insert into category(name, parent_id, template_id) values('MP3/MP4配件', 0, 1);
insert into category(name, parent_id, template_id) values('麦克风', 0, 1);
insert into category(name, parent_id, template_id) values('专业音频', 0, 1);
insert into category(name, parent_id, template_id) values('数码相框', 0, 1);
insert into category(name, parent_id, template_id) values('苹果配件', 0, 1);
insert into category(name, parent_id, template_id) values('电子教育', 549, 1);
insert into category(name, parent_id, template_id) values('电子词典', 592, 1);
insert into category(name, parent_id, template_id) values('电纸书', 592, 1);
insert into category(name, parent_id, template_id) values('录音笔', 592, 1);
insert into category(name, parent_id, template_id) values('复读机', 592, 1);
insert into category(name, parent_id, template_id) values('点读机/笔', 592, 1);
insert into category(name, parent_id, template_id) values('学生平板', 592, 1);
insert into category(name, parent_id, template_id) values('早教机', 592, 1);
insert into category(name, parent_id, template_id) values('家居家装', 0, 1);
insert into category(name, parent_id, template_id) values('家纺', 600, 1);
insert into category(name, parent_id, template_id) values('床品套件', 601, 1);
insert into category(name, parent_id, template_id) values('被子', 601, 1);
insert into category(name, parent_id, template_id) values('枕芯', 601, 1);
insert into category(name, parent_id, template_id) values('床单被罩', 601, 1);
insert into category(name, parent_id, template_id) values('毯子', 601, 1);
insert into category(name, parent_id, template_id) values('床垫/床褥', 601, 1);
insert into category(name, parent_id, template_id) values('蚊帐', 601, 1);
insert into category(name, parent_id, template_id) values('抱枕靠垫', 601, 1);
insert into category(name, parent_id, template_id) values('毛巾浴巾', 601, 1);
insert into category(name, parent_id, template_id) values('电热毯', 601, 1);
insert into category(name, parent_id, template_id) values('窗帘/窗纱', 601, 1);
insert into category(name, parent_id, template_id) values('布艺软饰', 601, 1);
insert into category(name, parent_id, template_id) values('凉席', 601, 1);
insert into category(name, parent_id, template_id) values('台灯', 0, 1);
insert into category(name, parent_id, template_id) values('节能灯', 0, 1);
insert into category(name, parent_id, template_id) values('装饰灯', 0, 1);
insert into category(name, parent_id, template_id) values('落地灯', 0, 1);
insert into category(name, parent_id, template_id) values('应急灯/手电', 0, 1);
insert into category(name, parent_id, template_id) values('吸顶灯', 0, 1);
insert into category(name, parent_id, template_id) values('五金电器', 0, 1);
insert into category(name, parent_id, template_id) values('筒灯射灯', 0, 1);
insert into category(name, parent_id, template_id) values('吊灯', 0, 1);
insert into category(name, parent_id, template_id) values('氛围照明', 0, 1);
insert into category(name, parent_id, template_id) values('生活日用', 600, 1);
insert into category(name, parent_id, template_id) values('收纳用品', 625, 1);
insert into category(name, parent_id, template_id) values('雨伞雨具', 625, 1);
insert into category(name, parent_id, template_id) values('浴室用品', 625, 1);
insert into category(name, parent_id, template_id) values('缝纫/针织用品', 625, 1);
insert into category(name, parent_id, template_id) values('洗晒/熨烫', 625, 1);
insert into category(name, parent_id, template_id) values('净化除味', 625, 1);
insert into category(name, parent_id, template_id) values('家装软饰', 600, 1);
insert into category(name, parent_id, template_id) values('桌布/罩件', 632, 1);
insert into category(name, parent_id, template_id) values('地毯地垫', 632, 1);
insert into category(name, parent_id, template_id) values('沙发垫套/椅垫', 632, 1);
insert into category(name, parent_id, template_id) values('相框/照片墙', 632, 1);
insert into category(name, parent_id, template_id) values('装饰字画', 632, 1);
insert into category(name, parent_id, template_id) values('节庆饰品', 632, 1);
insert into category(name, parent_id, template_id) values('手工/十字绣', 632, 1);
insert into category(name, parent_id, template_id) values('装饰摆件', 632, 1);
insert into category(name, parent_id, template_id) values('保暖防护', 632, 1);
insert into category(name, parent_id, template_id) values('帘艺隔断', 632, 1);
insert into category(name, parent_id, template_id) values('墙贴/装饰贴', 632, 1);
insert into category(name, parent_id, template_id) values('钟饰', 632, 1);
insert into category(name, parent_id, template_id) values('花瓶花艺', 632, 1);
insert into category(name, parent_id, template_id) values('香薰蜡烛', 632, 1);
insert into category(name, parent_id, template_id) values('创意家居', 632, 1);
insert into category(name, parent_id, template_id) values('清洁用品', 600, 1);
insert into category(name, parent_id, template_id) values('纸品湿巾', 648, 1);
insert into category(name, parent_id, template_id) values('衣物清洁', 648, 1);
insert into category(name, parent_id, template_id) values('清洁工具', 648, 1);
insert into category(name, parent_id, template_id) values('驱虫用品', 648, 1);
insert into category(name, parent_id, template_id) values('家庭清洁', 648, 1);
insert into category(name, parent_id, template_id) values('皮具护理', 648, 1);
insert into category(name, parent_id, template_id) values('一次性用品', 648, 1);
insert into category(name, parent_id, template_id) values('宠物生活', 600, 1);
insert into category(name, parent_id, template_id) values('宠物主粮', 656, 1);
insert into category(name, parent_id, template_id) values('宠物零食', 656, 1);
insert into category(name, parent_id, template_id) values('医疗保健', 656, 1);
insert into category(name, parent_id, template_id) values('家居日用', 656, 1);
insert into category(name, parent_id, template_id) values('宠物玩具', 656, 1);
insert into category(name, parent_id, template_id) values('出行装备', 656, 1);
insert into category(name, parent_id, template_id) values('洗护美容', 656, 1);
insert into category(name, parent_id, template_id) values('厨具', 0, 1);
insert into category(name, parent_id, template_id) values('烹饪锅具', 664, 1);
insert into category(name, parent_id, template_id) values('炒锅', 665, 1);
insert into category(name, parent_id, template_id) values('煎锅', 665, 1);
insert into category(name, parent_id, template_id) values('压力锅', 665, 1);
insert into category(name, parent_id, template_id) values('蒸锅', 665, 1);
insert into category(name, parent_id, template_id) values('汤锅', 665, 1);
insert into category(name, parent_id, template_id) values('奶锅', 665, 1);
insert into category(name, parent_id, template_id) values('锅具套装', 665, 1);
insert into category(name, parent_id, template_id) values('煲类', 665, 1);
insert into category(name, parent_id, template_id) values('水壶', 665, 1);
insert into category(name, parent_id, template_id) values('火锅', 665, 1);
insert into category(name, parent_id, template_id) values('刀剪菜板', 664, 1);
insert into category(name, parent_id, template_id) values('菜刀', 676, 1);
insert into category(name, parent_id, template_id) values('剪刀', 676, 1);
insert into category(name, parent_id, template_id) values('刀具套装', 676, 1);
insert into category(name, parent_id, template_id) values('砧板', 676, 1);
insert into category(name, parent_id, template_id) values('瓜果刀/刨', 676, 1);
insert into category(name, parent_id, template_id) values('多功能刀', 676, 1);
insert into category(name, parent_id, template_id) values('厨房配件', 664, 1);
insert into category(name, parent_id, template_id) values('保鲜盒', 683, 1);
insert into category(name, parent_id, template_id) values('烘焙/烧烤', 683, 1);
insert into category(name, parent_id, template_id) values('饭盒/提锅', 683, 1);
insert into category(name, parent_id, template_id) values('储物/置物架', 683, 1);
insert into category(name, parent_id, template_id) values('厨房DIY/小工具', 683, 1);
insert into category(name, parent_id, template_id) values('水具酒具', 664, 1);
insert into category(name, parent_id, template_id) values('塑料杯', 689, 1);
insert into category(name, parent_id, template_id) values('运动水壶', 689, 1);
insert into category(name, parent_id, template_id) values('玻璃杯', 689, 1);
insert into category(name, parent_id, template_id) values('陶瓷/马克杯', 689, 1);
insert into category(name, parent_id, template_id) values('保温杯', 689, 1);
insert into category(name, parent_id, template_id) values('保温壶', 689, 1);
insert into category(name, parent_id, template_id) values('酒杯/酒具', 689, 1);
insert into category(name, parent_id, template_id) values('杯具套装', 689, 1);
insert into category(name, parent_id, template_id) values('餐具', 664, 1);
insert into category(name, parent_id, template_id) values('餐具套装', 698, 1);
insert into category(name, parent_id, template_id) values('碗/碟/盘', 698, 1);
insert into category(name, parent_id, template_id) values('筷勺/刀叉', 698, 1);
insert into category(name, parent_id, template_id) values('果盘/果篮', 698, 1);
insert into category(name, parent_id, template_id) values('茶具/咖啡具', 664, 1);
insert into category(name, parent_id, template_id) values('整套茶具', 703, 1);
insert into category(name, parent_id, template_id) values('茶杯', 703, 1);
insert into category(name, parent_id, template_id) values('茶壶', 703, 1);
insert into category(name, parent_id, template_id) values('茶盘茶托', 703, 1);
insert into category(name, parent_id, template_id) values('茶叶罐', 703, 1);
insert into category(name, parent_id, template_id) values('茶具配件', 703, 1);
insert into category(name, parent_id, template_id) values('茶宠摆件', 703, 1);
insert into category(name, parent_id, template_id) values('咖啡具', 703, 1);
insert into category(name, parent_id, template_id) values('其他', 703, 1);
insert into category(name, parent_id, template_id) values('服饰内衣', 0, 1);
insert into category(name, parent_id, template_id) values('女装', 713, 1);
insert into category(name, parent_id, template_id) values('T恤', 714, 1);
insert into category(name, parent_id, template_id) values('衬衫', 714, 1);
insert into category(name, parent_id, template_id) values('针织衫', 714, 1);
insert into category(name, parent_id, template_id) values('雪纺衫', 714, 1);
insert into category(name, parent_id, template_id) values('卫衣', 714, 1);
insert into category(name, parent_id, template_id) values('马甲', 714, 1);
insert into category(name, parent_id, template_id) values('连衣裙', 714, 1);
insert into category(name, parent_id, template_id) values('半身裙', 714, 1);
insert into category(name, parent_id, template_id) values('牛仔裤', 714, 1);
insert into category(name, parent_id, template_id) values('休闲裤', 714, 1);
insert into category(name, parent_id, template_id) values('打底裤', 714, 1);
insert into category(name, parent_id, template_id) values('正装裤', 714, 1);
insert into category(name, parent_id, template_id) values('小西装', 714, 1);
insert into category(name, parent_id, template_id) values('短外套', 714, 1);
insert into category(name, parent_id, template_id) values('风衣', 714, 1);
insert into category(name, parent_id, template_id) values('毛呢大衣', 714, 1);
insert into category(name, parent_id, template_id) values('真皮皮衣', 714, 1);
insert into category(name, parent_id, template_id) values('棉服', 714, 1);
insert into category(name, parent_id, template_id) values('羽绒服', 714, 1);
insert into category(name, parent_id, template_id) values('大码女装', 714, 1);
insert into category(name, parent_id, template_id) values('中老年女装', 714, 1);
insert into category(name, parent_id, template_id) values('婚纱', 714, 1);
insert into category(name, parent_id, template_id) values('打底衫', 714, 1);
insert into category(name, parent_id, template_id) values('旗袍/唐装', 714, 1);
insert into category(name, parent_id, template_id) values('加绒裤', 714, 1);
insert into category(name, parent_id, template_id) values('吊带/背心', 714, 1);
insert into category(name, parent_id, template_id) values('羊绒衫', 714, 1);
insert into category(name, parent_id, template_id) values('短裤', 714, 1);
insert into category(name, parent_id, template_id) values('皮草', 714, 1);
insert into category(name, parent_id, template_id) values('礼服', 714, 1);
insert into category(name, parent_id, template_id) values('仿皮皮衣', 714, 1);
insert into category(name, parent_id, template_id) values('羊毛衫', 714, 1);
insert into category(name, parent_id, template_id) values('设计师/潮牌', 714, 1);
insert into category(name, parent_id, template_id) values('男装', 713, 1);
insert into category(name, parent_id, template_id) values('POLO衫', 748, 1);
insert into category(name, parent_id, template_id) values('马甲/背心', 748, 1);
insert into category(name, parent_id, template_id) values('夹克', 748, 1);
insert into category(name, parent_id, template_id) values('西服', 748, 1);
insert into category(name, parent_id, template_id) values('西裤', 748, 1);
insert into category(name, parent_id, template_id) values('西服套装', 748, 1);
insert into category(name, parent_id, template_id) values('大码男装', 748, 1);
insert into category(name, parent_id, template_id) values('中老年男装', 748, 1);
insert into category(name, parent_id, template_id) values('唐装/中山装', 748, 1);
insert into category(name, parent_id, template_id) values('工装', 748, 1);
insert into category(name, parent_id, template_id) values('卫裤/运动裤', 748, 1);
insert into category(name, parent_id, template_id) values('内衣', 713, 1);
insert into category(name, parent_id, template_id) values('文胸', 760, 1);
insert into category(name, parent_id, template_id) values('女式内裤', 760, 1);
insert into category(name, parent_id, template_id) values('男式内裤', 760, 1);
insert into category(name, parent_id, template_id) values('睡衣/家居服', 760, 1);
insert into category(name, parent_id, template_id) values('塑身美体', 760, 1);
insert into category(name, parent_id, template_id) values('泳衣', 760, 1);
insert into category(name, parent_id, template_id) values('抹胸', 760, 1);
insert into category(name, parent_id, template_id) values('连裤袜/丝袜', 760, 1);
insert into category(name, parent_id, template_id) values('美腿袜', 760, 1);
insert into category(name, parent_id, template_id) values('商务男袜', 760, 1);
insert into category(name, parent_id, template_id) values('保暖内衣', 760, 1);
insert into category(name, parent_id, template_id) values('情侣睡衣', 760, 1);
insert into category(name, parent_id, template_id) values('文胸套装', 760, 1);
insert into category(name, parent_id, template_id) values('少女文胸', 760, 1);
insert into category(name, parent_id, template_id) values('休闲棉袜', 760, 1);
insert into category(name, parent_id, template_id) values('大码内衣', 760, 1);
insert into category(name, parent_id, template_id) values('内衣配件', 760, 1);
insert into category(name, parent_id, template_id) values('打底裤袜', 760, 1);
insert into category(name, parent_id, template_id) values('秋衣秋裤', 760, 1);
insert into category(name, parent_id, template_id) values('情趣内衣', 760, 1);
insert into category(name, parent_id, template_id) values('服饰配件', 713, 1);
insert into category(name, parent_id, template_id) values('太阳镜', 781, 1);
insert into category(name, parent_id, template_id) values('光学镜架/镜片', 781, 1);
insert into category(name, parent_id, template_id) values('围巾/手套/帽子套装', 781, 1);
insert into category(name, parent_id, template_id) values('袖扣', 781, 1);
insert into category(name, parent_id, template_id) values('棒球帽', 781, 1);
insert into category(name, parent_id, template_id) values('毛线帽', 781, 1);
insert into category(name, parent_id, template_id) values('遮阳帽', 781, 1);
insert into category(name, parent_id, template_id) values('老花镜', 781, 1);
insert into category(name, parent_id, template_id) values('装饰眼镜', 781, 1);
insert into category(name, parent_id, template_id) values('防辐射眼镜', 781, 1);
insert into category(name, parent_id, template_id) values('游泳镜', 781, 1);
insert into category(name, parent_id, template_id) values('女士丝巾/围巾/披肩', 781, 1);
insert into category(name, parent_id, template_id) values('男士丝巾/围巾', 781, 1);
insert into category(name, parent_id, template_id) values('鸭舌帽', 781, 1);
insert into category(name, parent_id, template_id) values('贝雷帽', 781, 1);
insert into category(name, parent_id, template_id) values('礼帽', 781, 1);
insert into category(name, parent_id, template_id) values('真皮手套', 781, 1);
insert into category(name, parent_id, template_id) values('毛线手套', 781, 1);
insert into category(name, parent_id, template_id) values('防晒手套', 781, 1);
insert into category(name, parent_id, template_id) values('男士腰带/礼盒', 781, 1);
insert into category(name, parent_id, template_id) values('女士腰带/礼盒', 781, 1);
insert into category(name, parent_id, template_id) values('钥匙扣', 781, 1);
insert into category(name, parent_id, template_id) values('遮阳伞/雨伞', 781, 1);
insert into category(name, parent_id, template_id) values('口罩', 781, 1);
insert into category(name, parent_id, template_id) values('耳罩/耳包', 781, 1);
insert into category(name, parent_id, template_id) values('假领', 781, 1);
insert into category(name, parent_id, template_id) values('毛线/布面料', 781, 1);
insert into category(name, parent_id, template_id) values('领带/领结/领带夹', 781, 1);
insert into category(name, parent_id, template_id) values('鞋靴', 0, 1);
insert into category(name, parent_id, template_id) values('流行男鞋', 810, 1);
insert into category(name, parent_id, template_id) values('商务休闲鞋', 811, 1);
insert into category(name, parent_id, template_id) values('正装鞋', 811, 1);
insert into category(name, parent_id, template_id) values('休闲鞋', 811, 1);
insert into category(name, parent_id, template_id) values('凉鞋/沙滩鞋', 811, 1);
insert into category(name, parent_id, template_id) values('男靴', 811, 1);
insert into category(name, parent_id, template_id) values('拖鞋/人字拖', 811, 1);
insert into category(name, parent_id, template_id) values('雨鞋/雨靴', 811, 1);
insert into category(name, parent_id, template_id) values('传统布鞋', 811, 1);
insert into category(name, parent_id, template_id) values('鞋配件', 811, 1);
insert into category(name, parent_id, template_id) values('帆布鞋', 811, 1);
insert into category(name, parent_id, template_id) values('增高鞋', 811, 1);
insert into category(name, parent_id, template_id) values('工装鞋', 811, 1);
insert into category(name, parent_id, template_id) values('定制鞋', 811, 1);
insert into category(name, parent_id, template_id) values('时尚女鞋', 810, 1);
insert into category(name, parent_id, template_id) values('高跟鞋', 825, 1);
insert into category(name, parent_id, template_id) values('单鞋', 825, 1);
insert into category(name, parent_id, template_id) values('女靴', 825, 1);
insert into category(name, parent_id, template_id) values('雪地靴', 825, 1);
insert into category(name, parent_id, template_id) values('踝靴', 825, 1);
insert into category(name, parent_id, template_id) values('筒靴', 825, 1);
insert into category(name, parent_id, template_id) values('妈妈鞋', 825, 1);
insert into category(name, parent_id, template_id) values('特色鞋', 825, 1);
insert into category(name, parent_id, template_id) values('鱼嘴鞋', 825, 1);
insert into category(name, parent_id, template_id) values('布鞋/绣花鞋', 825, 1);
insert into category(name, parent_id, template_id) values('马丁靴', 825, 1);
insert into category(name, parent_id, template_id) values('坡跟鞋', 825, 1);
insert into category(name, parent_id, template_id) values('松糕鞋', 825, 1);
insert into category(name, parent_id, template_id) values('内增高', 825, 1);
insert into category(name, parent_id, template_id) values('防水台', 825, 1);
insert into category(name, parent_id, template_id) values('礼品箱包', 0, 1);
insert into category(name, parent_id, template_id) values('潮流女包', 841, 1);
insert into category(name, parent_id, template_id) values('钱包', 842, 1);
insert into category(name, parent_id, template_id) values('手拿包/晚宴包', 842, 1);
insert into category(name, parent_id, template_id) values('单肩包', 842, 1);
insert into category(name, parent_id, template_id) values('双肩包', 842, 1);
insert into category(name, parent_id, template_id) values('手提包', 842, 1);
insert into category(name, parent_id, template_id) values('斜挎包', 842, 1);
insert into category(name, parent_id, template_id) values('钥匙包', 842, 1);
insert into category(name, parent_id, template_id) values('卡包/零钱包', 842, 1);
insert into category(name, parent_id, template_id) values('精品男包', 841, 1);
insert into category(name, parent_id, template_id) values('钱包/卡包', 851, 1);
insert into category(name, parent_id, template_id) values('男士手包', 851, 1);
insert into category(name, parent_id, template_id) values('商务公文包', 851, 1);
insert into category(name, parent_id, template_id) values('单肩/斜挎包', 851, 1);
insert into category(name, parent_id, template_id) values('功能箱包', 841, 1);
insert into category(name, parent_id, template_id) values('电脑包', 856, 1);
insert into category(name, parent_id, template_id) values('拉杆箱/拉杆包', 856, 1);
insert into category(name, parent_id, template_id) values('旅行包', 856, 1);
insert into category(name, parent_id, template_id) values('旅行配件', 856, 1);
insert into category(name, parent_id, template_id) values('休闲运动包', 856, 1);
insert into category(name, parent_id, template_id) values('登山包', 856, 1);
insert into category(name, parent_id, template_id) values('妈咪包', 856, 1);
insert into category(name, parent_id, template_id) values('书包', 856, 1);
insert into category(name, parent_id, template_id) values('腰包/胸包', 856, 1);
insert into category(name, parent_id, template_id) values('礼品', 841, 1);
insert into category(name, parent_id, template_id) values('火机烟具', 866, 1);
insert into category(name, parent_id, template_id) values('礼品文具', 866, 1);
insert into category(name, parent_id, template_id) values('军刀军具', 866, 1);
insert into category(name, parent_id, template_id) values('收藏品', 866, 1);
insert into category(name, parent_id, template_id) values('工艺礼品', 866, 1);
insert into category(name, parent_id, template_id) values('创意礼品', 866, 1);
insert into category(name, parent_id, template_id) values('礼盒礼券', 866, 1);
insert into category(name, parent_id, template_id) values('鲜花绿植', 866, 1);
insert into category(name, parent_id, template_id) values('婚庆用品', 866, 1);
insert into category(name, parent_id, template_id) values('京东卡', 866, 1);
insert into category(name, parent_id, template_id) values('美妆礼品', 866, 1);
insert into category(name, parent_id, template_id) values('地方礼品', 866, 1);
insert into category(name, parent_id, template_id) values('古董把玩', 866, 1);
insert into category(name, parent_id, template_id) values('奢侈品', 841, 1);
insert into category(name, parent_id, template_id) values('箱包', 880, 1);
insert into category(name, parent_id, template_id) values('服饰', 880, 1);
insert into category(name, parent_id, template_id) values('腰带', 880, 1);
insert into category(name, parent_id, template_id) values('太阳镜/眼镜框', 880, 1);
insert into category(name, parent_id, template_id) values('配件', 880, 1);
insert into category(name, parent_id, template_id) values('饰品', 880, 1);
insert into category(name, parent_id, template_id) values('名品腕表', 880, 1);
insert into category(name, parent_id, template_id) values('高档化妆品', 880, 1);
insert into category(name, parent_id, template_id) values('婚庆', 841, 1);
insert into category(name, parent_id, template_id) values('婚嫁首饰', 889, 1);
insert into category(name, parent_id, template_id) values('婚纱摄影', 889, 1);
insert into category(name, parent_id, template_id) values('婚纱礼服', 889, 1);
insert into category(name, parent_id, template_id) values('婚庆服务', 889, 1);
insert into category(name, parent_id, template_id) values('婚庆礼品/用品', 889, 1);
insert into category(name, parent_id, template_id) values('婚宴', 889, 1);
insert into category(name, parent_id, template_id) values('珠宝', 0, 1);
insert into category(name, parent_id, template_id) values('时尚饰品', 896, 1);
insert into category(name, parent_id, template_id) values('项链', 897, 1);
insert into category(name, parent_id, template_id) values('手链/脚链', 897, 1);
insert into category(name, parent_id, template_id) values('戒指', 897, 1);
insert into category(name, parent_id, template_id) values('耳饰', 897, 1);
insert into category(name, parent_id, template_id) values('头饰', 897, 1);
insert into category(name, parent_id, template_id) values('胸针', 897, 1);
insert into category(name, parent_id, template_id) values('婚庆饰品', 897, 1);
insert into category(name, parent_id, template_id) values('饰品配件', 897, 1);
insert into category(name, parent_id, template_id) values('纯金K金饰品', 896, 1);
insert into category(name, parent_id, template_id) values('吊坠/项链', 906, 1);
insert into category(name, parent_id, template_id) values('手镯/手链/脚链', 906, 1);
insert into category(name, parent_id, template_id) values('金银投资', 896, 1);
insert into category(name, parent_id, template_id) values('工艺金', 909, 1);
insert into category(name, parent_id, template_id) values('工艺银', 909, 1);
insert into category(name, parent_id, template_id) values('银饰', 896, 1);
insert into category(name, parent_id, template_id) values('戒指/耳饰', 912, 1);
insert into category(name, parent_id, template_id) values('宝宝银饰', 912, 1);
insert into category(name, parent_id, template_id) values('千足银手镯', 912, 1);
insert into category(name, parent_id, template_id) values('钻石', 896, 1);
insert into category(name, parent_id, template_id) values('裸钻', 916, 1);
insert into category(name, parent_id, template_id) values('项链/吊坠', 916, 1);
insert into category(name, parent_id, template_id) values('手镯/手链', 916, 1);
insert into category(name, parent_id, template_id) values('翡翠玉石', 896, 1);
insert into category(name, parent_id, template_id) values('手镯/手串', 920, 1);
insert into category(name, parent_id, template_id) values('挂件/摆件/把件', 920, 1);
insert into category(name, parent_id, template_id) values('高值收藏', 920, 1);
insert into category(name, parent_id, template_id) values('水晶玛瑙', 896, 1);
insert into category(name, parent_id, template_id) values('头饰/胸针', 924, 1);
insert into category(name, parent_id, template_id) values('摆件/挂件', 924, 1);
insert into category(name, parent_id, template_id) values('彩宝', 896, 1);
insert into category(name, parent_id, template_id) values('铂金', 896, 1);
insert into category(name, parent_id, template_id) values('天然木饰', 896, 1);
insert into category(name, parent_id, template_id) values('小叶紫檀', 929, 1);
insert into category(name, parent_id, template_id) values('黄花梨', 929, 1);
insert into category(name, parent_id, template_id) values('沉香', 929, 1);
insert into category(name, parent_id, template_id) values('金丝楠', 929, 1);
insert into category(name, parent_id, template_id) values('菩提', 929, 1);
insert into category(name, parent_id, template_id) values('珍珠', 896, 1);
insert into category(name, parent_id, template_id) values('吊坠', 935, 1);
insert into category(name, parent_id, template_id) values('手链', 935, 1);
insert into category(name, parent_id, template_id) values('运动健康', 0, 1);
insert into category(name, parent_id, template_id) values('运动鞋包', 938, 1);
insert into category(name, parent_id, template_id) values('板鞋', 939, 1);
insert into category(name, parent_id, template_id) values('专项运动鞋', 939, 1);
insert into category(name, parent_id, template_id) values('跑步鞋', 939, 1);
insert into category(name, parent_id, template_id) values('篮球鞋', 939, 1);
insert into category(name, parent_id, template_id) values('足球鞋', 939, 1);
insert into category(name, parent_id, template_id) values('训练鞋', 939, 1);
insert into category(name, parent_id, template_id) values('乒羽网鞋', 939, 1);
insert into category(name, parent_id, template_id) values('拖鞋', 939, 1);
insert into category(name, parent_id, template_id) values('运动包', 939, 1);
insert into category(name, parent_id, template_id) values('运动服饰', 938, 1);
insert into category(name, parent_id, template_id) values('运动配饰', 949, 1);
insert into category(name, parent_id, template_id) values('毛衫/线衫', 949, 1);
insert into category(name, parent_id, template_id) values('乒羽网服', 949, 1);
insert into category(name, parent_id, template_id) values('训练服', 949, 1);
insert into category(name, parent_id, template_id) values('运动背心', 949, 1);
insert into category(name, parent_id, template_id) values('卫衣/套头衫', 949, 1);
insert into category(name, parent_id, template_id) values('夹克/风衣', 949, 1);
insert into category(name, parent_id, template_id) values('运动裤', 949, 1);
insert into category(name, parent_id, template_id) values('骑行运动', 938, 1);
insert into category(name, parent_id, template_id) values('折叠车', 958, 1);
insert into category(name, parent_id, template_id) values('山地车/公路车', 958, 1);
insert into category(name, parent_id, template_id) values('其他整车', 958, 1);
insert into category(name, parent_id, template_id) values('骑行服', 958, 1);
insert into category(name, parent_id, template_id) values('骑行装备', 958, 1);
insert into category(name, parent_id, template_id) values('垂钓用品', 938, 1);
insert into category(name, parent_id, template_id) values('鱼竿鱼线', 964, 1);
insert into category(name, parent_id, template_id) values('浮漂鱼饵', 964, 1);
insert into category(name, parent_id, template_id) values('钓鱼桌椅', 964, 1);
insert into category(name, parent_id, template_id) values('钓鱼配件', 964, 1);
insert into category(name, parent_id, template_id) values('钓箱鱼包', 964, 1);
insert into category(name, parent_id, template_id) values('游泳用品', 938, 1);
insert into category(name, parent_id, template_id) values('泳镜', 970, 1);
insert into category(name, parent_id, template_id) values('泳帽', 970, 1);
insert into category(name, parent_id, template_id) values('游泳包防水包', 970, 1);
insert into category(name, parent_id, template_id) values('女士泳衣', 970, 1);
insert into category(name, parent_id, template_id) values('男士泳衣', 970, 1);
insert into category(name, parent_id, template_id) values('比基尼', 970, 1);
insert into category(name, parent_id, template_id) values('户外鞋服', 938, 1);
insert into category(name, parent_id, template_id) values('冲锋衣裤', 977, 1);
insert into category(name, parent_id, template_id) values('速干衣裤', 977, 1);
insert into category(name, parent_id, template_id) values('滑雪服', 977, 1);
insert into category(name, parent_id, template_id) values('休闲衣裤', 977, 1);
insert into category(name, parent_id, template_id) values('抓绒衣裤', 977, 1);
insert into category(name, parent_id, template_id) values('软壳衣裤', 977, 1);
insert into category(name, parent_id, template_id) values('户外风衣', 977, 1);
insert into category(name, parent_id, template_id) values('功能内衣', 977, 1);
insert into category(name, parent_id, template_id) values('军迷服饰', 977, 1);
insert into category(name, parent_id, template_id) values('登山鞋', 977, 1);
insert into category(name, parent_id, template_id) values('徒步鞋', 977, 1);
insert into category(name, parent_id, template_id) values('越野跑鞋', 977, 1);
insert into category(name, parent_id, template_id) values('溯溪鞋', 977, 1);
insert into category(name, parent_id, template_id) values('沙滩/凉拖', 977, 1);
insert into category(name, parent_id, template_id) values('户外袜', 977, 1);
insert into category(name, parent_id, template_id) values('户外装备', 938, 1);
insert into category(name, parent_id, template_id) values('帐篷/垫子', 993, 1);
insert into category(name, parent_id, template_id) values('睡袋/吊床', 993, 1);
insert into category(name, parent_id, template_id) values('登山攀岩', 993, 1);
insert into category(name, parent_id, template_id) values('背包', 993, 1);
insert into category(name, parent_id, template_id) values('户外配饰', 993, 1);
insert into category(name, parent_id, template_id) values('户外照明', 993, 1);
insert into category(name, parent_id, template_id) values('户外仪表', 993, 1);
insert into category(name, parent_id, template_id) values('户外工具', 993, 1);
insert into category(name, parent_id, template_id) values('望远镜', 993, 1);
insert into category(name, parent_id, template_id) values('旅游用品', 993, 1);
insert into category(name, parent_id, template_id) values('便携桌椅床', 993, 1);
insert into category(name, parent_id, template_id) values('野餐烧烤', 993, 1);
insert into category(name, parent_id, template_id) values('军迷用品', 993, 1);
insert into category(name, parent_id, template_id) values('救援装备', 993, 1);
insert into category(name, parent_id, template_id) values('滑雪装备', 993, 1);
insert into category(name, parent_id, template_id) values('极限户外', 993, 1);
insert into category(name, parent_id, template_id) values('冲浪潜水', 993, 1);
insert into category(name, parent_id, template_id) values('健身训练', 938, 1);
insert into category(name, parent_id, template_id) values('综合训练器', 1011, 1);
insert into category(name, parent_id, template_id) values('其他大型器械', 1011, 1);
insert into category(name, parent_id, template_id) values('哑铃', 1011, 1);
insert into category(name, parent_id, template_id) values('仰卧板/收腹机', 1011, 1);
insert into category(name, parent_id, template_id) values('其他中小型器材', 1011, 1);
insert into category(name, parent_id, template_id) values('瑜伽舞蹈', 1011, 1);
insert into category(name, parent_id, template_id) values('武术搏击', 1011, 1);
insert into category(name, parent_id, template_id) values('健身车/动感单车', 1011, 1);
insert into category(name, parent_id, template_id) values('跑步机', 1011, 1);
insert into category(name, parent_id, template_id) values('运动护具', 1011, 1);
insert into category(name, parent_id, template_id) values('纤体瑜伽', 938, 1);
insert into category(name, parent_id, template_id) values('瑜伽垫', 1022, 1);
insert into category(name, parent_id, template_id) values('瑜伽服', 1022, 1);
insert into category(name, parent_id, template_id) values('瑜伽配件', 1022, 1);
insert into category(name, parent_id, template_id) values('瑜伽套装', 1022, 1);
insert into category(name, parent_id, template_id) values('舞蹈鞋服', 1022, 1);
insert into category(name, parent_id, template_id) values('体育用品', 938, 1);
insert into category(name, parent_id, template_id) values('羽毛球', 1028, 1);
insert into category(name, parent_id, template_id) values('乒乓球', 1028, 1);
insert into category(name, parent_id, template_id) values('篮球', 1028, 1);
insert into category(name, parent_id, template_id) values('足球', 1028, 1);
insert into category(name, parent_id, template_id) values('网球', 1028, 1);
insert into category(name, parent_id, template_id) values('排球', 1028, 1);
insert into category(name, parent_id, template_id) values('高尔夫', 1028, 1);
insert into category(name, parent_id, template_id) values('台球', 1028, 1);
insert into category(name, parent_id, template_id) values('棋牌麻将', 1028, 1);
insert into category(name, parent_id, template_id) values('轮滑滑板', 1028, 1);
insert into category(name, parent_id, template_id) values('彩票、旅行、充值、票务', 0, 1);
insert into category(name, parent_id, template_id) values('彩票', 1039, 1);
insert into category(name, parent_id, template_id) values('双色球', 1040, 1);
insert into category(name, parent_id, template_id) values('大乐透', 1040, 1);
insert into category(name, parent_id, template_id) values('福彩3D', 1040, 1);
insert into category(name, parent_id, template_id) values('排列三', 1040, 1);
insert into category(name, parent_id, template_id) values('排列五', 1040, 1);
insert into category(name, parent_id, template_id) values('七星彩', 1040, 1);
insert into category(name, parent_id, template_id) values('七乐彩', 1040, 1);
insert into category(name, parent_id, template_id) values('竞彩足球', 1040, 1);
insert into category(name, parent_id, template_id) values('竞彩篮球', 1040, 1);
insert into category(name, parent_id, template_id) values('新时时彩', 1040, 1);
insert into category(name, parent_id, template_id) values('机票', 1039, 1);
insert into category(name, parent_id, template_id) values('国内机票', 1051, 1);
insert into category(name, parent_id, template_id) values('酒店', 1039, 1);
insert into category(name, parent_id, template_id) values('国内酒店', 1053, 1);
insert into category(name, parent_id, template_id) values('酒店团购', 1053, 1);
insert into category(name, parent_id, template_id) values('旅行', 1039, 1);
insert into category(name, parent_id, template_id) values('度假', 1056, 1);
insert into category(name, parent_id, template_id) values('景点', 1056, 1);
insert into category(name, parent_id, template_id) values('租车', 1056, 1);
insert into category(name, parent_id, template_id) values('火车票', 1056, 1);
insert into category(name, parent_id, template_id) values('旅游团购', 1056, 1);
insert into category(name, parent_id, template_id) values('充值', 1039, 1);
insert into category(name, parent_id, template_id) values('手机充值', 1062, 1);
insert into category(name, parent_id, template_id) values('游戏', 1039, 1);
insert into category(name, parent_id, template_id) values('游戏点卡', 1064, 1);
insert into category(name, parent_id, template_id) values('QQ充值', 1064, 1);
insert into category(name, parent_id, template_id) values('票务', 1039, 1);
insert into category(name, parent_id, template_id) values('电影票', 1067, 1);
insert into category(name, parent_id, template_id) values('演唱会', 1067, 1);
insert into category(name, parent_id, template_id) values('话剧歌剧', 1067, 1);
insert into category(name, parent_id, template_id) values('音乐会', 1067, 1);
insert into category(name, parent_id, template_id) values('体育赛事', 1067, 1);
insert into category(name, parent_id, template_id) values('舞蹈芭蕾', 1067, 1);
insert into category(name, parent_id, template_id) values('戏曲综艺', 1067, 1);
insert into category(name, parent_id, template_id) values('分类测试_毛祥溢', 15, 1);
insert into category(name, parent_id, template_id) values('小家电', 66, 1);
insert into category(name, parent_id, template_id) values('英文小说', 11, 1);
insert into category(name, parent_id, template_id) values('火锅涮锅', 683, 1);
insert into category(name, parent_id, template_id) values('手电筒', 1076, 1);
insert into category(name, parent_id, template_id) values('照妖镜', 1076, 1);
insert into category(name, parent_id, template_id) values('AA', 261, 1);
insert into category(name, parent_id, template_id) values('蓝宝石', 916, 1);
insert into category(name, parent_id, template_id) values('电子小说', 2, 1);
insert into category(name, parent_id, template_id) values('上网本', 153, 1);
insert into category(name, parent_id, template_id) values('婴儿礼服', 325, 1);
insert into category(name, parent_id, template_id) values('电子漫画书', 2, 1);
insert into category(name, parent_id, template_id) values('不移动软盘', 177, 1);
insert into category(name, parent_id, template_id) values('购机送流量', 531, 1);
insert into category(name, parent_id, template_id) values('二手家电', 66, 1);
insert into category(name, parent_id, template_id) values('电子教科书', 2, 1);
insert into category(name, parent_id, template_id) values('儿童电脑', 592, 1);
insert into category(name, parent_id, template_id) values('测试手机分类', 528, 1);
insert into category(name, parent_id, template_id) values('测试餐具', 698, 1);
insert into category(name, parent_id, template_id) values('黑马电视', 152, 1);
insert into category(name, parent_id, template_id) values('电子文学', 2, 1);
insert into category(name, parent_id, template_id) values('电子画报', 2, 1);

insert into category_brand (category_id, brand_id) values(68, 5);
insert into category_brand (category_id, brand_id) values(68, 15);
insert into category_brand (category_id, brand_id) values(68, 25);
insert into category_brand (category_id, brand_id) values(134, 14);
insert into category_brand (category_id, brand_id) values(154, 19);
insert into category_brand (category_id, brand_id) values(528, 1);
insert into category_brand (category_id, brand_id) values(528, 4);
insert into category_brand (category_id, brand_id) values(528, 19);
insert into category_brand (category_id, brand_id) values(528, 42);
insert into category_brand (category_id, brand_id) values(1001, 121);
insert into category_brand (category_id, brand_id) values(1076, 19);
insert into category_brand (category_id, brand_id) values(1076, 42);

